# GENERATED by tools/gen_ast.py from schema/ast-schema.json
# (pandoc-api-version 1.23.1.2). Do not edit; regenerate instead.
"""pandoc's document AST as Python dataclasses.

One class per pandoc-types constructor, with fields in the Haskell order.
``Pandoc.from_json`` / ``Pandoc.to_json`` (and ``from_json`` / ``to_json``
for any node type) convert to and from pandoc's JSON.
"""

from __future__ import annotations

import enum
import typing
from dataclasses import dataclass, field


class Node:
    """Base class of every AST node."""

    __slots__ = ()

    def to_json(self) -> typing.Any:  # noqa: D102
        """This node as pandoc's JSON (Python lists, dicts, str, ...)."""
        return _ENCODERS[_type_of(self)](self)

    @classmethod
    def from_json(cls, j: typing.Any) -> typing.Self:
        """A node of this type from pandoc's JSON."""
        return _DECODERS[_type_of_class(cls)](j)


PANDOC_API_VERSION = (1, 23, 1, 2)


@dataclass(slots=True)
class Pandoc(Node):
    meta: Meta
    blocks: list[Block]


class Block(Node):
    """Any constructor of pandoc's ``Block``."""

    __slots__ = ()


@dataclass(slots=True)
class Plain(Block):
    content: list[Inline]


@dataclass(slots=True)
class Para(Block):
    content: list[Inline]


@dataclass(slots=True)
class LineBlock(Block):
    content: list[list[Inline]]


@dataclass(slots=True)
class CodeBlock(Block):
    attr: Attr
    text: str


@dataclass(slots=True)
class RawBlock(Block):
    format: Format
    text: str


@dataclass(slots=True)
class BlockQuote(Block):
    content: list[Block]


@dataclass(slots=True)
class OrderedList(Block):
    list_attributes: ListAttributes
    content: list[list[Block]]


@dataclass(slots=True)
class BulletList(Block):
    content: list[list[Block]]


@dataclass(slots=True)
class DefinitionList(Block):
    content: list[tuple[list[Inline], list[list[Block]]]]


@dataclass(slots=True)
class Header(Block):
    level: int
    attr: Attr
    content: list[Inline]


@dataclass(slots=True)
class HorizontalRule(Block):
    pass


@dataclass(slots=True)
class Table(Block):
    attr: Attr
    caption: Caption
    col_specs: list[ColSpec]
    table_head: TableHead
    table_bodies: list[TableBody]
    table_foot: TableFoot


@dataclass(slots=True)
class Figure(Block):
    attr: Attr
    caption: Caption
    content: list[Block]


@dataclass(slots=True)
class Div(Block):
    attr: Attr
    content: list[Block]


class MetaValue(Node):
    """Any constructor of pandoc's ``MetaValue``."""

    __slots__ = ()


@dataclass(slots=True)
class MetaMap(MetaValue):
    content: dict[str, MetaValue]


@dataclass(slots=True)
class MetaList(MetaValue):
    content: list[MetaValue]


@dataclass(slots=True)
class MetaBool(MetaValue):
    value: bool


@dataclass(slots=True)
class MetaString(MetaValue):
    text: str


@dataclass(slots=True)
class MetaInlines(MetaValue):
    content: list[Inline]


@dataclass(slots=True)
class MetaBlocks(MetaValue):
    content: list[Block]


class Inline(Node):
    """Any constructor of pandoc's ``Inline``."""

    __slots__ = ()


@dataclass(slots=True)
class Str(Inline):
    text: str


@dataclass(slots=True)
class Emph(Inline):
    content: list[Inline]


@dataclass(slots=True)
class Underline(Inline):
    content: list[Inline]


@dataclass(slots=True)
class Strong(Inline):
    content: list[Inline]


@dataclass(slots=True)
class Strikeout(Inline):
    content: list[Inline]


@dataclass(slots=True)
class Superscript(Inline):
    content: list[Inline]


@dataclass(slots=True)
class Subscript(Inline):
    content: list[Inline]


@dataclass(slots=True)
class SmallCaps(Inline):
    content: list[Inline]


@dataclass(slots=True)
class Quoted(Inline):
    quote_type: QuoteType
    content: list[Inline]


@dataclass(slots=True)
class Cite(Inline):
    citations: list[Citation]
    content: list[Inline]


@dataclass(slots=True)
class Code(Inline):
    attr: Attr
    text: str


@dataclass(slots=True)
class Space(Inline):
    pass


@dataclass(slots=True)
class SoftBreak(Inline):
    pass


@dataclass(slots=True)
class LineBreak(Inline):
    pass


@dataclass(slots=True)
class Math(Inline):
    math_type: MathType
    text: str


@dataclass(slots=True)
class RawInline(Inline):
    format: Format
    text: str


@dataclass(slots=True)
class Link(Inline):
    attr: Attr
    content: list[Inline]
    target: Target


@dataclass(slots=True)
class Image(Inline):
    attr: Attr
    content: list[Inline]
    target: Target


@dataclass(slots=True)
class Note(Inline):
    content: list[Block]


@dataclass(slots=True)
class Span(Inline):
    attr: Attr
    content: list[Inline]


@dataclass(slots=True)
class Attr(Node):
    """pandoc's ``Attr`` (a tuple, encoded as a JSON array)."""

    identifier: str = ""
    classes: list[str] = field(default_factory=list)
    attributes: list[tuple[str, str]] = field(default_factory=list)


@dataclass(slots=True)
class ListAttributes(Node):
    """pandoc's ``ListAttributes`` (a tuple, encoded as a JSON array)."""

    start: int
    style: ListNumberStyle
    delimiter: ListNumberDelim


@dataclass(slots=True)
class Caption(Node):
    short_caption: ShortCaption | None
    content: list[Block]


@dataclass(slots=True)
class ColSpec(Node):
    """pandoc's ``ColSpec`` (a tuple, encoded as a JSON array)."""

    alignment: Alignment
    width: ColWidthBase


@dataclass(slots=True)
class TableHead(Node):
    attr: Attr
    rows: list[Row]


@dataclass(slots=True)
class TableBody(Node):
    attr: Attr
    row_head_columns: RowHeadColumns
    head: list[Row]
    body: list[Row]


@dataclass(slots=True)
class TableFoot(Node):
    attr: Attr
    rows: list[Row]


class QuoteType(str, enum.Enum):
    """pandoc's ``QuoteType``."""

    SingleQuote = "SingleQuote"
    DoubleQuote = "DoubleQuote"


@dataclass(slots=True)
class Citation(Node):
    id: str
    prefix: list[Inline]
    suffix: list[Inline]
    mode: CitationMode
    note_num: int
    hash: int


class MathType(str, enum.Enum):
    """pandoc's ``MathType``."""

    DisplayMath = "DisplayMath"
    InlineMath = "InlineMath"


@dataclass(slots=True)
class Target(Node):
    """pandoc's ``Target`` (a tuple, encoded as a JSON array)."""

    url: str = ""
    title: str = ""


class ListNumberStyle(str, enum.Enum):
    """pandoc's ``ListNumberStyle``."""

    DefaultStyle = "DefaultStyle"
    Example = "Example"
    Decimal = "Decimal"
    LowerRoman = "LowerRoman"
    UpperRoman = "UpperRoman"
    LowerAlpha = "LowerAlpha"
    UpperAlpha = "UpperAlpha"


class ListNumberDelim(str, enum.Enum):
    """pandoc's ``ListNumberDelim``."""

    DefaultDelim = "DefaultDelim"
    Period = "Period"
    OneParen = "OneParen"
    TwoParens = "TwoParens"


class Alignment(str, enum.Enum):
    """pandoc's ``Alignment``."""

    AlignLeft = "AlignLeft"
    AlignRight = "AlignRight"
    AlignCenter = "AlignCenter"
    AlignDefault = "AlignDefault"


class ColWidthBase(Node):
    """Any constructor of pandoc's ``ColWidth``."""

    __slots__ = ()


@dataclass(slots=True)
class ColWidth(ColWidthBase):
    width: float


@dataclass(slots=True)
class ColWidthDefault(ColWidthBase):
    pass


@dataclass(slots=True)
class Row(Node):
    attr: Attr
    cells: list[Cell]


class CitationMode(str, enum.Enum):
    """pandoc's ``CitationMode``."""

    AuthorInText = "AuthorInText"
    SuppressAuthor = "SuppressAuthor"
    NormalCitation = "NormalCitation"


@dataclass(slots=True)
class Cell(Node):
    attr: Attr
    alignment: Alignment
    row_span: RowSpan
    col_span: ColSpan
    content: list[Block]


# type aliases and newtypes
Meta = dict[str, "MetaValue"]
Format = str
ShortCaption = list["Inline"]
RowHeadColumns = int
RowSpan = int
ColSpan = int


# JSON codecs, following pandoc-types' aeson instances


def _dec_Pandoc(j):
    _check_api_version(j.get("pandoc-api-version"))
    return Pandoc(_dec_Meta(j["meta"]), [_dec_Block(x0) for x0 in j["blocks"]])


def _enc_Pandoc(v):
    return {
        "pandoc-api-version": list(PANDOC_API_VERSION),
        "meta": _enc_Meta(v.meta),
        "blocks": [_enc_Block(x0) for x0 in v.blocks],
    }


def _dec_Meta(j):
    return {k0: _dec_MetaValue(x0) for k0, x0 in j.items()}


def _enc_Meta(v):
    return {k0: _enc_MetaValue(x0) for k0, x0 in v.items()}


_DEC_Block = {
    "Plain": lambda c: Plain([_dec_Inline(x0) for x0 in c]),
    "Para": lambda c: Para([_dec_Inline(x0) for x0 in c]),
    "LineBlock": lambda c: LineBlock([[_dec_Inline(x1) for x1 in x0] for x0 in c]),
    "CodeBlock": lambda c: CodeBlock(_dec_Attr(c[0]), c[1]),
    "RawBlock": lambda c: RawBlock(_dec_Format(c[0]), c[1]),
    "BlockQuote": lambda c: BlockQuote([_dec_Block(x0) for x0 in c]),
    "OrderedList": lambda c: OrderedList(
        _dec_ListAttributes(c[0]), [[_dec_Block(x1) for x1 in x0] for x0 in c[1]]
    ),
    "BulletList": lambda c: BulletList([[_dec_Block(x1) for x1 in x0] for x0 in c]),
    "DefinitionList": lambda c: DefinitionList(
        [
            (
                [_dec_Inline(x1) for x1 in x0[0]],
                [[_dec_Block(x2) for x2 in x1] for x1 in x0[1]],
            )
            for x0 in c
        ]
    ),
    "Header": lambda c: Header(c[0], _dec_Attr(c[1]), [_dec_Inline(x0) for x0 in c[2]]),
    "HorizontalRule": lambda c: HorizontalRule(),
    "Table": lambda c: Table(
        _dec_Attr(c[0]),
        _dec_Caption(c[1]),
        [_dec_ColSpec(x0) for x0 in c[2]],
        _dec_TableHead(c[3]),
        [_dec_TableBody(x0) for x0 in c[4]],
        _dec_TableFoot(c[5]),
    ),
    "Figure": lambda c: Figure(
        _dec_Attr(c[0]), _dec_Caption(c[1]), [_dec_Block(x0) for x0 in c[2]]
    ),
    "Div": lambda c: Div(_dec_Attr(c[0]), [_dec_Block(x0) for x0 in c[1]]),
}


def _dec_Block(j):
    return _DEC_Block[j["t"]](j.get("c"))


_ENC_Block = {
    Plain: lambda v: {"t": "Plain", "c": [_enc_Inline(x0) for x0 in v.content]},
    Para: lambda v: {"t": "Para", "c": [_enc_Inline(x0) for x0 in v.content]},
    LineBlock: lambda v: {
        "t": "LineBlock",
        "c": [[_enc_Inline(x1) for x1 in x0] for x0 in v.content],
    },
    CodeBlock: lambda v: {"t": "CodeBlock", "c": [_enc_Attr(v.attr), v.text]},
    RawBlock: lambda v: {"t": "RawBlock", "c": [_enc_Format(v.format), v.text]},
    BlockQuote: lambda v: {
        "t": "BlockQuote",
        "c": [_enc_Block(x0) for x0 in v.content],
    },
    OrderedList: lambda v: {
        "t": "OrderedList",
        "c": [
            _enc_ListAttributes(v.list_attributes),
            [[_enc_Block(x1) for x1 in x0] for x0 in v.content],
        ],
    },
    BulletList: lambda v: {
        "t": "BulletList",
        "c": [[_enc_Block(x1) for x1 in x0] for x0 in v.content],
    },
    DefinitionList: lambda v: {
        "t": "DefinitionList",
        "c": [
            [
                [_enc_Inline(x1) for x1 in x0[0]],
                [[_enc_Block(x2) for x2 in x1] for x1 in x0[1]],
            ]
            for x0 in v.content
        ],
    },
    Header: lambda v: {
        "t": "Header",
        "c": [v.level, _enc_Attr(v.attr), [_enc_Inline(x0) for x0 in v.content]],
    },
    HorizontalRule: lambda v: {"t": "HorizontalRule"},
    Table: lambda v: {
        "t": "Table",
        "c": [
            _enc_Attr(v.attr),
            _enc_Caption(v.caption),
            [_enc_ColSpec(x0) for x0 in v.col_specs],
            _enc_TableHead(v.table_head),
            [_enc_TableBody(x0) for x0 in v.table_bodies],
            _enc_TableFoot(v.table_foot),
        ],
    },
    Figure: lambda v: {
        "t": "Figure",
        "c": [
            _enc_Attr(v.attr),
            _enc_Caption(v.caption),
            [_enc_Block(x0) for x0 in v.content],
        ],
    },
    Div: lambda v: {
        "t": "Div",
        "c": [_enc_Attr(v.attr), [_enc_Block(x0) for x0 in v.content]],
    },
}


def _enc_Block(v):
    return _ENC_Block[type(v)](v)


_DEC_MetaValue = {
    "MetaMap": lambda c: MetaMap({k0: _dec_MetaValue(x0) for k0, x0 in c.items()}),
    "MetaList": lambda c: MetaList([_dec_MetaValue(x0) for x0 in c]),
    "MetaBool": lambda c: MetaBool(c),
    "MetaString": lambda c: MetaString(c),
    "MetaInlines": lambda c: MetaInlines([_dec_Inline(x0) for x0 in c]),
    "MetaBlocks": lambda c: MetaBlocks([_dec_Block(x0) for x0 in c]),
}


def _dec_MetaValue(j):
    return _DEC_MetaValue[j["t"]](j.get("c"))


_ENC_MetaValue = {
    MetaMap: lambda v: {
        "t": "MetaMap",
        "c": {k0: _enc_MetaValue(x0) for k0, x0 in v.content.items()},
    },
    MetaList: lambda v: {
        "t": "MetaList",
        "c": [_enc_MetaValue(x0) for x0 in v.content],
    },
    MetaBool: lambda v: {"t": "MetaBool", "c": v.value},
    MetaString: lambda v: {"t": "MetaString", "c": v.text},
    MetaInlines: lambda v: {
        "t": "MetaInlines",
        "c": [_enc_Inline(x0) for x0 in v.content],
    },
    MetaBlocks: lambda v: {
        "t": "MetaBlocks",
        "c": [_enc_Block(x0) for x0 in v.content],
    },
}


def _enc_MetaValue(v):
    return _ENC_MetaValue[type(v)](v)


_DEC_Inline = {
    "Str": lambda c: Str(c),
    "Emph": lambda c: Emph([_dec_Inline(x0) for x0 in c]),
    "Underline": lambda c: Underline([_dec_Inline(x0) for x0 in c]),
    "Strong": lambda c: Strong([_dec_Inline(x0) for x0 in c]),
    "Strikeout": lambda c: Strikeout([_dec_Inline(x0) for x0 in c]),
    "Superscript": lambda c: Superscript([_dec_Inline(x0) for x0 in c]),
    "Subscript": lambda c: Subscript([_dec_Inline(x0) for x0 in c]),
    "SmallCaps": lambda c: SmallCaps([_dec_Inline(x0) for x0 in c]),
    "Quoted": lambda c: Quoted(_dec_QuoteType(c[0]), [_dec_Inline(x0) for x0 in c[1]]),
    "Cite": lambda c: Cite(
        [_dec_Citation(x0) for x0 in c[0]], [_dec_Inline(x0) for x0 in c[1]]
    ),
    "Code": lambda c: Code(_dec_Attr(c[0]), c[1]),
    "Space": lambda c: Space(),
    "SoftBreak": lambda c: SoftBreak(),
    "LineBreak": lambda c: LineBreak(),
    "Math": lambda c: Math(_dec_MathType(c[0]), c[1]),
    "RawInline": lambda c: RawInline(_dec_Format(c[0]), c[1]),
    "Link": lambda c: Link(
        _dec_Attr(c[0]), [_dec_Inline(x0) for x0 in c[1]], _dec_Target(c[2])
    ),
    "Image": lambda c: Image(
        _dec_Attr(c[0]), [_dec_Inline(x0) for x0 in c[1]], _dec_Target(c[2])
    ),
    "Note": lambda c: Note([_dec_Block(x0) for x0 in c]),
    "Span": lambda c: Span(_dec_Attr(c[0]), [_dec_Inline(x0) for x0 in c[1]]),
}


def _dec_Inline(j):
    return _DEC_Inline[j["t"]](j.get("c"))


_ENC_Inline = {
    Str: lambda v: {"t": "Str", "c": v.text},
    Emph: lambda v: {"t": "Emph", "c": [_enc_Inline(x0) for x0 in v.content]},
    Underline: lambda v: {"t": "Underline", "c": [_enc_Inline(x0) for x0 in v.content]},
    Strong: lambda v: {"t": "Strong", "c": [_enc_Inline(x0) for x0 in v.content]},
    Strikeout: lambda v: {"t": "Strikeout", "c": [_enc_Inline(x0) for x0 in v.content]},
    Superscript: lambda v: {
        "t": "Superscript",
        "c": [_enc_Inline(x0) for x0 in v.content],
    },
    Subscript: lambda v: {"t": "Subscript", "c": [_enc_Inline(x0) for x0 in v.content]},
    SmallCaps: lambda v: {"t": "SmallCaps", "c": [_enc_Inline(x0) for x0 in v.content]},
    Quoted: lambda v: {
        "t": "Quoted",
        "c": [_enc_QuoteType(v.quote_type), [_enc_Inline(x0) for x0 in v.content]],
    },
    Cite: lambda v: {
        "t": "Cite",
        "c": [
            [_enc_Citation(x0) for x0 in v.citations],
            [_enc_Inline(x0) for x0 in v.content],
        ],
    },
    Code: lambda v: {"t": "Code", "c": [_enc_Attr(v.attr), v.text]},
    Space: lambda v: {"t": "Space"},
    SoftBreak: lambda v: {"t": "SoftBreak"},
    LineBreak: lambda v: {"t": "LineBreak"},
    Math: lambda v: {"t": "Math", "c": [_enc_MathType(v.math_type), v.text]},
    RawInline: lambda v: {"t": "RawInline", "c": [_enc_Format(v.format), v.text]},
    Link: lambda v: {
        "t": "Link",
        "c": [
            _enc_Attr(v.attr),
            [_enc_Inline(x0) for x0 in v.content],
            _enc_Target(v.target),
        ],
    },
    Image: lambda v: {
        "t": "Image",
        "c": [
            _enc_Attr(v.attr),
            [_enc_Inline(x0) for x0 in v.content],
            _enc_Target(v.target),
        ],
    },
    Note: lambda v: {"t": "Note", "c": [_enc_Block(x0) for x0 in v.content]},
    Span: lambda v: {
        "t": "Span",
        "c": [_enc_Attr(v.attr), [_enc_Inline(x0) for x0 in v.content]],
    },
}


def _enc_Inline(v):
    return _ENC_Inline[type(v)](v)


def _dec_Attr(j):
    return Attr(
        j[0],
        [x0 for x0 in j[1]],
        [
            (
                x0[0],
                x0[1],
            )
            for x0 in j[2]
        ],
    )


def _enc_Attr(v):
    return [v.identifier, v.classes, [[x0[0], x0[1]] for x0 in v.attributes]]


def _dec_Format(j):
    return j


def _enc_Format(v):
    return v


def _dec_ListAttributes(j):
    return ListAttributes(j[0], _dec_ListNumberStyle(j[1]), _dec_ListNumberDelim(j[2]))


def _enc_ListAttributes(v):
    return [v.start, _enc_ListNumberStyle(v.style), _enc_ListNumberDelim(v.delimiter)]


def _dec_Caption(j):
    return Caption(
        (None if j[0] is None else _dec_ShortCaption(j[0])),
        [_dec_Block(x0) for x0 in j[1]],
    )


def _enc_Caption(v):
    return [
        (None if v.short_caption is None else _enc_ShortCaption(v.short_caption)),
        [_enc_Block(x0) for x0 in v.content],
    ]


def _dec_ColSpec(j):
    return ColSpec(_dec_Alignment(j[0]), _dec_ColWidth(j[1]))


def _enc_ColSpec(v):
    return [_enc_Alignment(v.alignment), _enc_ColWidth(v.width)]


def _dec_TableHead(j):
    return TableHead(_dec_Attr(j[0]), [_dec_Row(x0) for x0 in j[1]])


def _enc_TableHead(v):
    return [_enc_Attr(v.attr), [_enc_Row(x0) for x0 in v.rows]]


def _dec_TableBody(j):
    return TableBody(
        _dec_Attr(j[0]),
        _dec_RowHeadColumns(j[1]),
        [_dec_Row(x0) for x0 in j[2]],
        [_dec_Row(x0) for x0 in j[3]],
    )


def _enc_TableBody(v):
    return [
        _enc_Attr(v.attr),
        _enc_RowHeadColumns(v.row_head_columns),
        [_enc_Row(x0) for x0 in v.head],
        [_enc_Row(x0) for x0 in v.body],
    ]


def _dec_TableFoot(j):
    return TableFoot(_dec_Attr(j[0]), [_dec_Row(x0) for x0 in j[1]])


def _enc_TableFoot(v):
    return [_enc_Attr(v.attr), [_enc_Row(x0) for x0 in v.rows]]


def _dec_QuoteType(j):
    return QuoteType(j["t"])


def _enc_QuoteType(v):
    return {"t": v.value}


def _dec_Citation(j):
    return Citation(
        j["citationId"],
        [_dec_Inline(x0) for x0 in j["citationPrefix"]],
        [_dec_Inline(x0) for x0 in j["citationSuffix"]],
        _dec_CitationMode(j["citationMode"]),
        j["citationNoteNum"],
        j["citationHash"],
    )


def _enc_Citation(v):
    return {
        "citationId": v.id,
        "citationPrefix": [_enc_Inline(x0) for x0 in v.prefix],
        "citationSuffix": [_enc_Inline(x0) for x0 in v.suffix],
        "citationMode": _enc_CitationMode(v.mode),
        "citationNoteNum": v.note_num,
        "citationHash": v.hash,
    }


def _dec_MathType(j):
    return MathType(j["t"])


def _enc_MathType(v):
    return {"t": v.value}


def _dec_Target(j):
    return Target(j[0], j[1])


def _enc_Target(v):
    return [v.url, v.title]


def _dec_ListNumberStyle(j):
    return ListNumberStyle(j["t"])


def _enc_ListNumberStyle(v):
    return {"t": v.value}


def _dec_ListNumberDelim(j):
    return ListNumberDelim(j["t"])


def _enc_ListNumberDelim(v):
    return {"t": v.value}


def _dec_ShortCaption(j):
    return [_dec_Inline(x0) for x0 in j]


def _enc_ShortCaption(v):
    return [_enc_Inline(x0) for x0 in v]


def _dec_Alignment(j):
    return Alignment(j["t"])


def _enc_Alignment(v):
    return {"t": v.value}


_DEC_ColWidth = {
    "ColWidth": lambda c: ColWidth(float(c)),
    "ColWidthDefault": lambda c: ColWidthDefault(),
}


def _dec_ColWidth(j):
    return _DEC_ColWidth[j["t"]](j.get("c"))


_ENC_ColWidth = {
    ColWidth: lambda v: {"t": "ColWidth", "c": v.width},
    ColWidthDefault: lambda v: {"t": "ColWidthDefault"},
}


def _enc_ColWidth(v):
    return _ENC_ColWidth[type(v)](v)


def _dec_Row(j):
    return Row(_dec_Attr(j[0]), [_dec_Cell(x0) for x0 in j[1]])


def _enc_Row(v):
    return [_enc_Attr(v.attr), [_enc_Cell(x0) for x0 in v.cells]]


def _dec_RowHeadColumns(j):
    return j


def _enc_RowHeadColumns(v):
    return v


def _dec_CitationMode(j):
    return CitationMode(j["t"])


def _enc_CitationMode(v):
    return {"t": v.value}


def _dec_Cell(j):
    return Cell(
        _dec_Attr(j[0]),
        _dec_Alignment(j[1]),
        _dec_RowSpan(j[2]),
        _dec_ColSpan(j[3]),
        [_dec_Block(x0) for x0 in j[4]],
    )


def _enc_Cell(v):
    return [
        _enc_Attr(v.attr),
        _enc_Alignment(v.alignment),
        _enc_RowSpan(v.row_span),
        _enc_ColSpan(v.col_span),
        [_enc_Block(x0) for x0 in v.content],
    ]


def _dec_RowSpan(j):
    return j


def _enc_RowSpan(v):
    return v


def _dec_ColSpan(j):
    return j


def _enc_ColSpan(v):
    return v


# pandoc type of each class (constructor classes map to their type)
_TYPE_OF: dict[type, str] = {
    Pandoc: "Pandoc",
    Block: "Block",
    Plain: "Block",
    Para: "Block",
    LineBlock: "Block",
    CodeBlock: "Block",
    RawBlock: "Block",
    BlockQuote: "Block",
    OrderedList: "Block",
    BulletList: "Block",
    DefinitionList: "Block",
    Header: "Block",
    HorizontalRule: "Block",
    Table: "Block",
    Figure: "Block",
    Div: "Block",
    MetaValue: "MetaValue",
    MetaMap: "MetaValue",
    MetaList: "MetaValue",
    MetaBool: "MetaValue",
    MetaString: "MetaValue",
    MetaInlines: "MetaValue",
    MetaBlocks: "MetaValue",
    Inline: "Inline",
    Str: "Inline",
    Emph: "Inline",
    Underline: "Inline",
    Strong: "Inline",
    Strikeout: "Inline",
    Superscript: "Inline",
    Subscript: "Inline",
    SmallCaps: "Inline",
    Quoted: "Inline",
    Cite: "Inline",
    Code: "Inline",
    Space: "Inline",
    SoftBreak: "Inline",
    LineBreak: "Inline",
    Math: "Inline",
    RawInline: "Inline",
    Link: "Inline",
    Image: "Inline",
    Note: "Inline",
    Span: "Inline",
    Attr: "Attr",
    ListAttributes: "ListAttributes",
    Caption: "Caption",
    ColSpec: "ColSpec",
    TableHead: "TableHead",
    TableBody: "TableBody",
    TableFoot: "TableFoot",
    QuoteType: "QuoteType",
    Citation: "Citation",
    MathType: "MathType",
    Target: "Target",
    ListNumberStyle: "ListNumberStyle",
    ListNumberDelim: "ListNumberDelim",
    Alignment: "Alignment",
    ColWidthBase: "ColWidth",
    ColWidth: "ColWidth",
    ColWidthDefault: "ColWidth",
    Row: "Row",
    CitationMode: "CitationMode",
    Cell: "Cell",
}


def _check_api_version(v):
    if v is None or list(v[:2]) != list(PANDOC_API_VERSION[:2]):
        raise ValueError(
            f"pandoc-api-version {v} is incompatible with {PANDOC_API_VERSION}"
        )


_DECODERS = {n[5:]: f for n, f in globals().items() if n.startswith("_dec_")}
_ENCODERS = {n[5:]: f for n, f in globals().items() if n.startswith("_enc_")}


def _type_of_class(cls: type) -> str:
    try:
        return _TYPE_OF[cls]
    except KeyError:
        raise TypeError(f"{cls.__name__} is not a pandoc AST type") from None


def _type_of(v: object) -> str:
    return _type_of_class(type(v))


def from_json(j: typing.Any) -> Pandoc:
    """A document from pandoc's JSON (as parsed by json.loads)."""
    return _dec_Pandoc(j)


def to_json(doc: Pandoc) -> typing.Any:
    """A document as pandoc's JSON (for json.dumps)."""
    return _enc_Pandoc(doc)
